# Uncomment the next line to define a global platform for your project

use_frameworks!

platform :ios, '11.0'

target '${POD_NAME}-Example' do
  pod '${POD_NAME}', :path => '../'

  target '${POD_NAME}_Tests' do
    inherit! :search_paths

    ${INCLUDED_PODS}
  end
end
