# Uncomment the next line to define a global platform for your project

# 官方仓库源
source 'https://github.com/CocoaPods/Specs.git'


platform :ios, '11.0'

inhibit_all_warnings!

use_frameworks!
install! 'cocoapods', :preserve_pod_file_structure => true

def commonPods 
  
  pod 'SwifterKnife', :git => 'https://github.com/CoderLouie/SwifterKnife.git', :branch => 'develop'
  pod 'SnapKit', :git => 'https://github.com/CoderLouie/SnapKit.git', :branch => 'my_source'

end

target '${POD_NAME}-Example' do
  commonPods
  pod '${POD_NAME}', :path => '../'

end
